# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true


distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 8
  distributed_port: 29671
  nprocs_per_node: 2
  find_unused_parameters: true

task:
  _name: wavlm_pretraining
  data: ???   # overwite this value in the command line
  label_dir: ???
  labels: ???
  label_rate: ${model.label_rate}
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: true # must be consistent with extractor
  noise_apply_prob: 0.0
  noise_db_range: "-5_20"
  interf_speech_db_range: "-5_5"

dataset:
  train_subset: train960
  valid_subset: dev
  num_workers: 6
  # max_tokens: 1400000
  max_tokens: 700000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 10000

criterion:
  _name: hubert
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10,]

optimization:
  max_update: 400000
  update_freq: [7]
  lr: [0.0005]
  clip_norm: 10.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wavlm
  label_rate: ???
  extractor_mode: 'layer_norm'
  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16
  activation_fn: 'gelu'
  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.0
  encoder_layerdrop: 0.0
  dropout_input: 0.0
  dropout_features: 0.0
  layer_norm_first: true
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  conv_bias: false
  feature_grad_mult: 1.0
  mask_length: 10
  mask_prob: 0.8
  mask_selection: 'static'
  mask_other: 0.0
  no_mask_overlap: false
  mask_min_space: 1
  mask_channel_length: 10
  mask_channel_prob: 0.0
  mask_channel_selection: 'static'
  mask_channel_other: 0.0
  no_mask_channel_overlap: false
  mask_channel_min_space: 1
  conv_pos: 128
  conv_pos_groups: 16
  relative_position_embedding: true
  num_buckets: 320
  max_distance: 800
  gru_rel_pos: true

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
